import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import api from "../auth/axios";
import PropertyVip from "../components/PropertyVip";

export default function Home({ propertiesVip }) {
  console.log(propertiesVip);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PropertyVip properties={propertiesVip} />
    </div>
  );
}

export const getStaticProps = async () => {
  const { data: propertiesVip } = await api.get("/api/properties/vip");
  return {
    props: {
      propertiesVip,
    },
  };
};
